# Generated by Django 3.2.9 on 2021-12-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_navbar_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.category'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='menu',
            field=models.CharField(max_length=100),
        ),
    ]
