# Generated by Django 3.2.9 on 2021-12-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20211226_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.category'),
        ),
    ]
