# Generated by Django 3.2.9 on 2021-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_navbar_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='pic',
            field=models.ImageField(upload_to='upload_images/'),
        ),
    ]
